// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CommandPaletteController from "./command_palette_controller"
application.register("command-palette", CommandPaletteController)

import ScannerController from "./scanner_controller"
application.register("scanner", ScannerController)

import MealController  from './meal_controller'
application.register('meals', MealController)

import { Autocomplete } from 'stimulus-autocomplete'
application.register('autocomplete', Autocomplete)

// Import and register all TailwindCSS Components
import { Alert, Autosave, Dropdown, Modal, Tabs, Popover, Toggle, Slideover } from "tailwindcss-stimulus-components"
application.register('alert', Alert)
application.register('autosave', Autosave)
application.register('dropdown', Dropdown)
application.register('modal', Modal)
application.register('tabs', Tabs)
application.register('popover', Popover)
application.register('toggle', Toggle)
application.register('slideover', Slideover)